"""updated folder structure

Revision ID: 0050b745b112
Revises: f5398ce93284
Create Date: 2025-06-17 03:14:20.422476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0050b745b112'
down_revision: Union[str, None] = 'f5398ce93284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('name', sa.String(), nullable=False))
    op.add_column('folders', sa.Column('path', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'folders', ['path'])
    op.drop_column('folders', 'foldername')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('foldername', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'folders', type_='unique')
    op.drop_column('folders', 'path')
    op.drop_column('folders', 'name')
    # ### end Alembic commands ###
