"""added foldername,storagesize in user

Revision ID: 012a172377b3
Revises: d072bc84db4b
Create Date: 2025-04-25 21:00:22.547742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012a172377b3'
down_revision: Union[str, None] = 'd072bc84db4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('foldername', sa.String(), nullable=True))
    op.add_column('users', sa.Column('storage_size', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'storage_size')
    op.drop_column('users', 'foldername')
    # ### end Alembic commands ###
