"""files,folder model added

Revision ID: 0f89bfe721db
Revises: 012a172377b3
Create Date: 2025-05-02 01:48:46.575156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f89bfe721db'
down_revision: Union[str, None] = '012a172377b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('root_foldername', sa.String(), nullable=True))
    op.drop_column('users', 'foldername')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('foldername', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'root_foldername')
    # ### end Alembic commands ###
