"""empty message

Revision ID: f5398ce93284
Revises: eeb9d4466ada
Create Date: 2025-06-17 01:21:23.713622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5398ce93284'
down_revision: Union[str, None] = 'eeb9d4466ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('folders', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('max_storage', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('storage_used', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('users', 'storage_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('storage_size', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'storage_used')
    op.drop_column('users', 'max_storage')
    op.drop_column('folders', 'created_at')
    op.drop_column('files', 'created_at')
    # ### end Alembic commands ###
